default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: postgresql://localhost:5432/tradelink_dev

test:
  <<: *default
  url: postgresql://localhost:5432/thr-test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
